language: ruby

cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - truffleruby-head

script: "bundle exec rake --trace"

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  recipients:
    - nahi@ruby-lang.org
